# Generated by Django 4.2.2 on 2023-10-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(max_length=200)),
                ('activity_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('total_elevation_gain', models.FloatField()),
                ('type', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=200)),
                ('location_state', models.CharField(max_length=200)),
                ('location_country', models.CharField(max_length=200)),
                ('mapid', models.CharField(max_length=200)),
                ('mappolyline', models.TextField(max_length=3000)),
                ('mapresource_state', models.IntegerField()),
                ('upload_id_str', models.CharField(max_length=200)),
                ('workout_type', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('athlete_id', 'activity_id')},
            },
        ),
    ]
