# Generated by Django 4.2.2 on 2023-10-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='upload_id_str',
            new_name='upload_id',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='workout_type',
        ),
    ]
