# Generated by Django 4.2.2 on 2023-10-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0002_rename_upload_id_str_activities_upload_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='description',
        ),
    ]
