# Generated by Django 4.2.2 on 2023-10-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0003_remove_activities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='athlete_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activities',
            name='mapid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activities',
            name='upload_id',
            field=models.IntegerField(),
        ),
    ]
