# Generated by Django 4.2.2 on 2023-10-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0006_alter_activities_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='upload_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
